"""otp code added

Revision ID: b0aaa4955f5d
Revises: ffd46d43e1ad
Create Date: 2026-01-26 17:13:05.438629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0aaa4955f5d'
down_revision: Union[str, Sequence[str], None] = 'ffd46d43e1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('pending_data', sa.JSON(), nullable=True))
    op.add_column('sessions', sa.Column('otp_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'otp_code')
    op.drop_column('sessions', 'pending_data')
    # ### end Alembic commands ###
