"""Add webhook_url and completed_data fields

Revision ID: b6039397e20d
Revises: b0aaa4955f5d
Create Date: 2026-01-31 17:36:59.851685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6039397e20d'
down_revision: Union[str, Sequence[str], None] = 'b0aaa4955f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('webhook_url', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('completed_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'completed_data')
    op.drop_column('companies', 'webhook_url')
    # ### end Alembic commands ###
